# Generated by Django 4.2.24 on 2025-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
