# Generated by Django 4.2.25 on 2025-10-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggos', '0002_dogprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dog_photos/'),
        ),
    ]
